FROM python:3.9-slim

#set working directory
WORKDIR /app

#copy requirements first (for better caching)
COPY requirements.txt .

#install dependencies
RUN pip install --no-cache-dir -r requirements.txt

#copy all application files
COPY . .

#expose port
EXPOSE 8000

#eun the application
CMD ["python", "run.py"]